<?php

/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do NOT edit it manually. Run `php artisan openapi:generate-server`.
 */

use Illuminate\Support\Facades\Route;

Route::get('blog/post/{code}', [\App\Http\ApiV1\Controllers\BlogController::class, 'postDetail'])->name('postDetail');
